### ISSUE TITLE
Comments on draft concept

### ISSUE THREAD

**Issue by sunitagrote** [unicef/drone-dpgtoolkit#1]
- Would suggest framing it broader than "collection of content for Drone4Good application" and inclusive of the fact that it will contain software, potentially data, models etc. The term "Digital Public Goods" might be good to use here, since it includes all of these categories by definition
- In terms of the purpose, I'd suggest making it a bit more action oriented and including not just use and access, but also submit and contribute to these DPGs
- For next steps, I'd like us to explore how we can source some of these potential DPGs - should we do some kind of comms campaign? Can Victor advise how maybe some of our existing collaborations could help with this? Could our engagement with ICAO?
-

**Comment by enonied4g** [comment]
Thanks for this Sunita, I'll incorporate these suggestions.

**Comment by enonied4g** [comment]
Please see the edited read-me document for the DPG toolkit.

**Comment by lacabra** [comment]
@enonied4g: If you think that your changes addressed this issue go ahead and close it with the button below. You are on the "driver seat" as the maintainer of this repo, and if you don't close issues like this, they will linger open forever. If @sunitagrote or others think that their comments have not been properly addressed, they can always open another issue :)

To @sunitagrote's question about comms, I don't have any specific advice other than the obvious asking DPGA's comms team to retweet or amplify any call to action that we make. I could reach to some of our tech partners directly, but I would wait until we have a bit more content around here.
