### ISSUE TITLE
Launch Inventory theme for DPG Drone Toolkit

### ISSUE THREAD

**Issue by jwflory** [unicef/drone-dpgtoolkit#3]
# Summary

Launch a new [Hugo](https://gohugo.io/)-based site using the [UNICEF Inventory theme](https://github.com/unicef/inventory-hugo-theme) for the DPG Drone Toolkit

# Background

Per discussion with @enonied4g and @Idadelveloper today, we want to create a new knowledge-base site for the DPG Drones Toolkit that Edmond is building out. To facilitate this work, we will use the same theme/format as seen on the [UNICEF Open Source Inventory](https://unicef.github.io/inventory/) site.

The soft launch of this site will not include content, but it will include a home page, categories, and metadata for this project.

# Details

@Idadelveloper will support with the initial bootstrapping of the Hugo site. I can help support on this and also on building out a CI pipeline to facilitate easy contributions and quality assurance checks.

We need @enonied4g to list out the initial categories he would like to use on the site, similar to how they are laid out on the Open Source Inventory. We also need @lacabra to add this repository to the [GitHub team](https://github.com/orgs/unicef/teams/drones-toolkit-admins/repositories) for this work.

# Outcome

There is a path forward to begin publishing content for the DPG Drones Toolkit and to also facilitate contributions from a wider audience.

**Comment by lacabra** [comment]
@jwflory: the unicef/drones-toolkit-admins team has been added as an admin to this repo.

**Comment by enonied4g** [comment]
Thanks everyone.
